import java.text.SimpleDateFormat;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    
    public static void main(String args[]) {
    	SimpleDateFormat sdf=new SimpleDateFormat( "yyyy-mm-dd");
    }
}

